// English copy. Same shape as it.mjs.

export default {
  locale: 'en-GB',
  common: {
    skip: 'Skip to content',
    official: 'Official website',
    brandSub: 'Trave · Monte Conero',
    menu: 'Menu', close: 'Close', langLabel: 'English',
    nav: { home: 'Home', casa: 'The house', galleria: 'Gallery', dintorni: 'Surroundings', prezzi: 'Rates', contatti: 'Contact' },
    check: 'Check availability', request: 'Request availability', checkShort: 'Check dates',
    call: 'Call', whatsapp: 'WhatsApp', email: 'Email', directions: 'Open in Google Maps',
    whatsappText: 'Hello, I would like to check availability at Casa in Campagna, Trave.',
    whatsappDates: 'Hello, I would like to check availability from {checkin} to {checkout} for {guests} guests.',
    breadcrumb: 'Breadcrumb',
    photoPlate: 'Pl.',
  },
  booking: {
    label: 'Check availability', checkin: 'Arrival', checkout: 'Departure', guests: 'Guests', max: 'max 6',
    submit: 'Check availability',
    micro: 'No-obligation request · Check-in from 15:00 · Check-out by 10:00',
    errDates: 'Departure must be after arrival.',
  },
  facts: [
    ['110 m²', 'Entire house'], ['6', 'Guests'], ['2 + 1', 'Bedrooms and sofa bed'], ['2', 'Bathrooms'], ['600 m', 'Scoglio del Trave'],
  ],
  trust: {
    whole: 'Entire house, just for you', parking: 'Gated private parking', pets: 'Pets welcome at no extra charge',
    lang: 'We reply in Italian and English', cin: 'CIN {cin}',
    score: 'Location rated {value}/10 by guests · source {source}, checked {date}',
  },
  direct: {
    eyebrow: 'Direct booking', title: 'Book with your host',
    line: 'Send us your dates: the people who look after the house reply directly with availability and a quote.',
    benefits: ['Direct contact, no middleman', 'Special requests, tailored', 'No payment to ask'],
    perksTitle: 'Only when you book here', copy: 'Copy code', copied: 'Copied',
  },
  ctaBand: {
    eyebrow: 'The Conero is waiting', title: 'Is the house free on your dates?',
    line: 'Send us your arrival, departure and number of guests.',
    small: 'Check-in from 15:00 · Check-out by 10:00 · IT / EN',
  },
  sticky: { line1: 'Entire house · up to 6 guests', onRequest: 'Rates on request', from: 'from {price} / night' },
  footer: {
    howTo: 'Getting here', contacts: 'Contact', pages: 'Pages', info: 'Information',
    response: 'We usually reply within {t}', times: 'Check-in from 15:00 · Check-out by 10:00',
    langs: 'Languages: Italian, English', privacy: 'Privacy', cookie: 'Cookies', madeBy: 'Website by Ctrl Studio',
    rates: 'Seasonal rates',
  },
  form: {
    title: 'Request a quote', hint: 'No payment now. We reply with availability and a quote.',
    name: 'Full name', email: 'Email', phone: 'Phone or WhatsApp', optional: 'optional',
    checkin: 'Arrival', checkout: 'Departure', guests: 'Guests', pets: 'Pets', no: 'No', yes: 'Yes',
    message: 'Message', messagePh: 'Expected arrival time, questions about the house, special requests',
    privacy: 'By sending this request you agree that we use your data only to reply to you.', privacyLink: 'Privacy notice',
    submit: 'Send request',
    subject: 'Availability request {checkin} / {checkout}',
    success: 'Thank you, we have received your request.',
    successMail: 'Your email app has opened with the request filled in: press Send to deliver it.',
    successWa: 'For a quicker reply you can also message us on WhatsApp.',
    noscript: 'Write to us at {email} or call {phone}.',
    errRequired: 'Required field.', errEmail: 'Please enter a valid email address.',
    seasonPrefix: 'Season: ',
    fields: { season: 'Season', estimate: 'Estimate', lang: 'Language' },
  },
  rates: {
    caption: 'Seasonal rates, entire house up to 6 guests',
    cols: ['Season', 'Dates', 'Nightly rate', 'Minimum stay', ''],
    onRequest: 'On request', from: 'from', perNight: '/ night', perWeek: 'per week',
    askRate: 'Ask for the rate', ask: 'Request', current: 'Current season',
    minNull: 'On request', minN: '{n} nights',
    changeover: 'Arrivals and departures on {day}',
    noteHouse: 'Prices for the entire house. Rates are given with the quote.',
    noteIndicative: 'Dates and rates are indicative and confirmed in the quote.',
    updated: 'Rates updated on {date}',
    statementTitle: 'Rates for the entire house, quoted for your dates',
    statementLine: 'The rate depends on the season and length of stay. Send us your dates and we reply with availability and a quote.',
    and: ' and ', fromDay: '', toDay: 'to',
    summaryOnRequest: 'Rate on request', summaryFrom: 'from {price} / night', summaryWhole: 'Entire house, up to 6 guests',
    summaryMicro: 'No payment is needed to send a request.',
    estimator: {
      open: 'Estimate your stay', title: 'Stay estimate', nights: '{n} nights', night: '1 night',
      total: 'Indicative total', quote: 'We will send you a quote for these dates.',
      micro: 'Indicative, non-binding estimate. The final price is the one in the quote.',
      minStay: 'The minimum stay in this period is {n} nights. Send the request anyway, we are happy to consider your dates.',
      tax: 'Tourist tax, not included: {amount}', cta: 'Request this stay', taxExcluded: 'tourist tax not included',
    },
    months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    days: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  },
  gallery: {
    filters: { all: 'All', interni: 'Inside', camere: 'Bedrooms', bagni: 'Bathrooms', esterni: 'Outside', dintorni: 'Surroundings' },
    count: '{n} photographs', label: 'Photo gallery', prev: 'Previous photo', next: 'Next photo', open: 'Open photo',
    filterLabel: 'Filter photos',
  },
  hero: {
    label: 'Photographs of the house', slide: '{n} of {total}', prev: 'Previous photo', next: 'Next photo',
    pause: 'Pause slideshow', play: 'Resume slideshow',
  },
  map: {
    load: 'Load the map (OpenStreetMap)', note: 'Loading the map connects you to openstreetmap.org.', title: 'Map: Contrada Trave 125',
  },
  distancesNote: 'Distances are approximate.',

  pages: {
    home: {
      title: 'Conero holiday home, 600 m from the sea | Casa in Campagna',
      desc: 'Entire 110 m² holiday home in Montacuto, Ancona: sleeps 6, fenced garden, free private parking, pets welcome. 1.1 km from Mezzavalle beach, about 5 km from Portonovo.',
      eyebrow: 'Holiday home on Monte Conero',
      h1: 'A country house between Monte Conero and the sea',
      lead: 'Entire house, 110 m², up to 6 guests. 600 m from Scoglio del Trave.',
      discover: 'Discover the house',
      intro: {
        eyebrow: 'The house',
        h2: 'Exposed beams, terracotta and the Conero from the window',
        text: 'At Trave, above the Conero coast, an entire house just for you: two bedrooms and a sofa bed, two bathrooms, an eat-in kitchen and a living room with a fireplace. Outside, a fenced garden and private parking.',
        text2: 'The sea is close: {mezzavalle} beach is 1.1 km away and the bay of {portonovo} about 5 km.',
      },
      spaces: {
        eyebrow: 'The spaces', h2: 'All the space of a house', link: 'The whole house',
        items: [
          ['soggiorno-travi', 'Living room with fireplace', 'A big dining table, sofas and the fireplace under the wooden beams.'],
          ['camera-matrimoniale', 'Two bedrooms', 'A double and a twin bedroom, plus a sofa bed.'],
          ['giardino-palma-mare', 'Fenced garden', 'Lawn, palms and a glimpse of the sea, safe for children and pets.'],
        ],
      },
      garden: {
        eyebrow: 'Outside', h2: 'The garden and the view',
        text: 'The garden is fenced and looks onto Monte Conero, with a glimpse of the sea between the trees. Pets are welcome at no extra charge and your car stays in the gated private car park.',
      },
      horizon: { eyebrow: 'Surroundings', h2: 'The Conero sea, a short walk away', link: 'Explore the surroundings' },
      rates: {
        eyebrow: 'Rates', h2: 'Rates by season', note: 'Rates for the entire house, up to 6 guests.',
        see: 'See the rates', quote: 'Request a quote',
      },
      amenities: { eyebrow: 'Amenities', h2: 'What you will find in the house', link: 'All amenities' },
      faq: { eyebrow: 'Questions', h2: 'Frequently asked questions' },
    },

    casa: {
      title: 'Conero holiday home for 6 with garden | Casa in Campagna',
      desc: 'A 110 m² house with exposed beams: double bedroom, twin bedroom, sofa bed, 2 bathrooms, kitchen, fireplace and a fenced garden looking onto the Conero.',
      eyebrow: 'The house', h1: 'A Conero holiday home for 6, with a garden',
      lead: 'An entire 110 m² house with exposed beams, terracotta floors and a fireplace.',
      spec: {
        eyebrow: 'At a glance', h2: 'The house in numbers',
        rows: [
          ['Size', '110 m², entire house'], ['Guests', 'up to 6'], ['Bedrooms', '2'],
          ['Beds', '1 double, 2 singles, 1 sofa bed'], ['Bathrooms', '2, one with bathtub and one with shower'],
          ['Entrance', 'private, with private parking'],
        ],
      },
      spaces: {
        eyebrow: 'The spaces', h2: 'Room by room',
        items: [
          { n: '01', h: 'Living room with fireplace', p: 'The heart of the house: a big dining table, two sofas, the TV and the fireplace, under a ceiling of wooden beams.', facts: ['Fireplace', 'Sofa bed', 'Flat-screen TV'], photos: ['soggiorno-travi', 'soggiorno-camino'] },
          { n: '02', h: 'Eat-in kitchen', p: 'A kitchen with a table, to make breakfast and dinner just as you would at home.', facts: ['Hob and oven', 'Microwave and fridge', 'Tea and coffee set'], photos: ['cucina'] },
          { n: '03', h: 'Double bedroom', p: 'Large and bright, with exposed beams, a wardrobe and air conditioning.', facts: ['Double bed', 'Air conditioning', 'Wardrobe'], photos: ['camera-matrimoniale', 'camera-matrimoniale-armadio'] },
          { n: '04', h: 'Twin bedroom', p: 'Good for children or friends, with a wardrobe and a window onto the greenery.', facts: ['Two single beds', 'Wardrobe'], photos: ['camera-doppia', 'camera-doppia-armadio'] },
          { n: '05', h: 'Two bathrooms', p: 'One with a bathtub and the washing machine, one with a shower. Both have a bidet, hairdryer and toiletries.', facts: ['Bathtub', 'Shower', 'Hairdryer'], photos: ['bagno-vasca', 'bagno-doccia', 'bagno-secondo'], triptych: 'Two bathrooms: one with a bathtub, one with a shower' },
          { n: '06', h: 'Sofa bed', p: 'The living room has a sofa bed for the fifth and sixth guest.', facts: ['Up to 6 guests in total'], photos: [] },
          { n: '07', h: 'Garden and parking', p: 'The fenced garden looks onto Monte Conero, with a glimpse of the sea. At the entrance, the gated private car park.', facts: ['Fenced garden', 'View of the Conero', 'Free parking'], photos: ['giardino-vista-conero', 'giardino-palma-mare', 'parcheggio-privato'] },
        ],
        toRates: 'See rates and availability',
      },
      amenities: {
        eyebrow: 'Amenities', h2: 'Amenities and house rules',
        groups: { dentro: 'Inside', fuori: 'Outside', regole: 'Rules', no: 'Not available' },
      },
    },

    galleria: {
      title: 'Photos of the Conero holiday home | Casa in Campagna',
      desc: '17 photos of the holiday home at Trave: living room with fireplace, bedrooms, kitchen, bathrooms, garden looking onto Monte Conero and Mezzavalle beach.',
      eyebrow: 'Gallery', h1: 'Photos of the house and garden on the Conero',
      lead: 'Inside, the garden and the sea a short walk away.',
      intro: 'The house has a living room with a fireplace and exposed beams, an eat-in kitchen, a double bedroom, a twin bedroom and two bathrooms. Outside there is a fenced garden looking onto Monte Conero, with a glimpse of the sea. You will also find Mezzavalle beach, 1.1 km from the house.',
      inline: 'Like the house? Check your dates',
    },

    dintorni: {
      title: 'Mezzavalle, Portonovo and Ancona nearby | Casa in Campagna',
      desc: 'Scoglio del Trave 600 m, Mezzavalle beach 1.1 km, Portonovo about 5 km, Ancona 6.6 km. How to reach the holiday home by car, train and plane.',
      eyebrow: 'Surroundings', h1: 'Mezzavalle, Portonovo and the Conero beaches near the house',
      lead: 'The house sits above the Conero coast, between Trave and Ancona.',
      distances: { eyebrow: 'Distances', h2: 'How far' },
      places: { eyebrow: 'Places', h2: 'The sea and the city' },
      arrive: {
        eyebrow: 'Getting here', h2: 'By car, train or plane',
        car: ['By car', 'Set your satnav to Contrada Trave 125, Montacuto. There is free gated private parking at the house.'],
        train: ['By train', 'Ancona station, 6.6 km from the house.'],
        plane: ['By plane', 'Ancona airport, 19 km from the house.'],
      },
      map: { eyebrow: 'Map', h2: 'Where we are' },
      tips: { eyebrow: 'Tips', h2: 'Tips from your host' },
    },

    prezzi: {
      title: 'Conero holiday home rates by season | Casa in Campagna',
      desc: 'Seasonal rates for the entire house, up to 6 guests, on the Conero. Request availability and a quote for your dates: your host replies directly.',
      descPrices: 'Conero holiday home from {price} a night for the entire house, up to 6 guests. Seasonal rates, request availability and a quote.',
      eyebrow: 'Rates', h1: 'Rates and availability for the Conero holiday home',
      lead: 'Rates for the entire house, up to 6 guests. Send us your dates for an exact quote.',
      seasons: { eyebrow: 'Seasons', h2: 'The right time for the Conero', intro: 'Rates are for the entire house, up to 6 guests.' },
      included: {
        eyebrow: 'What is included', h2: 'Included and good to know', always: 'Always included', know: 'Good to know',
        cleaning: 'Final cleaning', cleaningIncluded: 'Included', cleaningAmount: '{amount}',
        tax: 'Tourist tax', taxText: 'Comune di Ancona tourist tax not included, the amount is shown in the quote.',
        taxAmount: '{amount} per person per night, not included',
        deposit: 'Security deposit', cots: 'Cots and extra beds', cotsText: 'Not available',
        smoking: 'Smoking', smokingText: 'No smoking inside the house',
        payment: 'Payment', terms: 'Terms are given with the quote.',
      },
      how: {
        eyebrow: 'How to book', h2: 'Three steps, with a real person on the other side',
        steps: [
          ['Send your dates', 'Arrival, departure and number of guests, with the form, on WhatsApp or by phone.'],
          ['Receive your quote', 'We reply with availability and the price for the entire house.'],
          ['Confirm', 'Payment and cancellation terms are set out in the quote.'],
        ],
        confirm: 'You will receive a written confirmation with dates, amount and terms.',
      },
      quote: {
        eyebrow: 'Quote', h2: 'Request a quote',
        tiles: [['Send an email', 'Fill in the form below'], ['Call', ''], ['WhatsApp', 'Send us a message']],
      },
      faq: { eyebrow: 'Questions', h2: 'Questions about rates' },
      portal: 'Prefer a booking platform? You will also find us on',
    },

    contatti: {
      title: 'Contact and booking, Montacuto (Ancona) | Casa in Campagna',
      desc: '{address}. {channels} and a form with arrival and departure dates for the Conero holiday home.',
      channels: { phone: 'Phone', whatsapp: 'WhatsApp', email: 'email' },
      eyebrow: 'Contact', h1: 'Contact and bookings',
      lead: 'Write directly to your host: we reply in Italian and English.',
      card: { title: 'Direct contact', address: 'Address', times: 'Times', cin: 'CIN', langs: 'Languages', langsText: 'Italian, English' },
      map: { eyebrow: 'Getting here', h2: 'Where we are', station: 'Ancona station', airport: 'Ancona airport', more: 'All directions' },
      arrival: { eyebrow: 'Arrival', h2: 'On the day you arrive', text: 'Check-in from 15:00, check-out by 10:00. Please let us know your arrival time in advance.' },
    },

    privacy: {
      title: 'Privacy and cookies | Casa in Campagna', desc: 'Privacy and cookie notice for the Casa in Campagna website at Trave.',
      eyebrow: 'Notice', h1: 'Privacy and cookies',
      lead: 'How we use the data you send us with the request form.',
      sections: [
        ['Data controller', '{controller}'],
        ['What data', 'Name, email, phone if you give it, stay dates, number of guests and the message you write.'],
        ['Why', 'Only to reply to your request and prepare a quote (art. 6.1.b GDPR, pre-contractual steps).'],
        ['How long', '{retention}'],
        ['Who receives it', 'Data is not passed on to third parties. It may pass through the email or form service provider: {provider}.'],
        ['Your rights', 'You can ask for access, correction, deletion or restriction of your data by writing to the controller. You can lodge a complaint with the Garante per la protezione dei dati personali.'],
      ],
      cookieTitle: 'Cookies',
      cookie: 'This website uses no profiling cookies and no third-party cookies. Fonts are hosted on the website itself. The map loads from OpenStreetMap only if you press its button.',
      missing: 'to be completed with the controller details',
    },

    notFound: {
      title: 'Page not found | Casa in Campagna', h1: 'Page not found',
      lead: 'The page you are looking for does not exist or has moved.', home: 'Back to the home page', en: 'Pagina non trovata. Home in italiano',
    },
  },
};
