// Testi italiani. Regole: niente trattini lunghi, nessun confronto di prezzo con i portali,
// nessun fatto inventato. I segnaposto {x} vengono sostituiti dal build.

export default {
  locale: 'it-IT',
  common: {
    skip: 'Vai al contenuto',
    official: 'Sito ufficiale',
    brandSub: 'Trave · Monte Conero',
    menu: 'Menu', close: 'Chiudi', langLabel: 'Italiano',
    nav: { home: 'Home', casa: 'La casa', galleria: 'Galleria', dintorni: 'Dintorni', prezzi: 'Prezzi', contatti: 'Contatti' },
    check: 'Verifica disponibilità', request: 'Richiedi disponibilità', checkShort: 'Verifica date',
    call: 'Chiama', whatsapp: 'WhatsApp', email: 'Email', directions: 'Apri in Google Maps',
    whatsappText: 'Buongiorno, vorrei sapere la disponibilità della Casa in Campagna al Trave.',
    whatsappDates: 'Buongiorno, vorrei sapere la disponibilità dal {checkin} al {checkout} per {guests} ospiti.',
    breadcrumb: 'Percorso',
    photoPlate: 'Tav.',
  },
  booking: {
    label: 'Verifica disponibilità', checkin: 'Arrivo', checkout: 'Partenza', guests: 'Ospiti', max: 'max 6',
    submit: 'Verifica disponibilità',
    micro: 'Richiesta senza impegno · Check-in dalle 15:00 · Check-out entro le 10:00',
    errDates: 'La partenza deve essere successiva all\'arrivo.',
  },
  facts: [
    ['110 m²', 'Casa intera'], ['6', 'Ospiti'], ['2 + 1', 'Camere e divano letto'], ['2', 'Bagni'], ['600 m', 'Scoglio del Trave'],
  ],
  trust: {
    whole: 'Casa intera, solo per voi', parking: 'Parcheggio privato con sbarra', pets: 'Animali ammessi senza supplemento',
    lang: 'Rispondiamo in italiano e in inglese', cin: 'CIN {cin}',
    score: 'Posizione valutata {value}/10 dagli ospiti · fonte {source}, rilevato {date}',
  },
  direct: {
    eyebrow: 'Prenotazione diretta', title: 'Prenota con chi ti ospita',
    line: 'Scrivici le tue date: ti risponde direttamente chi si occupa della casa, con disponibilità e preventivo.',
    benefits: ['Contatto diretto, nessun intermediario', 'Richieste particolari su misura', 'Nessun pagamento per chiedere'],
    perksTitle: 'Solo prenotando qui', copy: 'Copia codice', copied: 'Copiato',
  },
  ctaBand: {
    eyebrow: 'Il Conero ti aspetta', title: 'La casa è libera nelle tue date?',
    line: 'Scrivici arrivo, partenza e numero di ospiti.',
    small: 'Check-in dalle 15:00 · Check-out entro le 10:00 · IT / EN',
  },
  sticky: { line1: 'Casa intera · fino a 6 ospiti', onRequest: 'Tariffe su richiesta', from: 'da {price} / notte' },
  footer: {
    howTo: 'Come arrivare', contacts: 'Contatti', pages: 'Pagine', info: 'Informazioni',
    response: 'Di solito rispondiamo entro {t}', times: 'Check-in dalle 15:00 · Check-out entro le 10:00',
    langs: 'Lingue: italiano, inglese', privacy: 'Privacy', cookie: 'Cookie', madeBy: 'Sito di Ctrl Studio',
    rates: 'Tariffe per stagione',
  },
  form: {
    title: 'Richiedi un preventivo', hint: 'Nessun pagamento ora. Ti rispondiamo con disponibilità e preventivo.',
    name: 'Nome e cognome', email: 'Email', phone: 'Telefono o WhatsApp', optional: 'facoltativo',
    checkin: 'Arrivo', checkout: 'Partenza', guests: 'Ospiti', pets: 'Animali', no: 'No', yes: 'Sì',
    message: 'Messaggio', messagePh: 'Orario di arrivo previsto, domande sulla casa, richieste particolari',
    privacy: 'Inviando la richiesta accetti che usiamo i tuoi dati solo per risponderti.', privacyLink: 'Informativa privacy',
    submit: 'Invia richiesta',
    subject: 'Richiesta disponibilità {checkin} / {checkout}',
    success: 'Grazie, abbiamo ricevuto la tua richiesta.',
    successMail: 'Si è aperta la tua app di posta con la richiesta già compilata: premi Invia per mandarcela.',
    successWa: 'Per una risposta più rapida puoi scriverci anche su WhatsApp.',
    noscript: 'Scrivici a {email} o chiama {phone}.',
    errRequired: 'Campo obbligatorio.', errEmail: 'Inserisci un indirizzo email valido.',
    seasonPrefix: 'Stagione: ',
    fields: { season: 'Stagione', estimate: 'Stima', lang: 'Lingua' },
  },
  rates: {
    caption: 'Tariffe per stagione, casa intera fino a 6 ospiti',
    cols: ['Stagione', 'Periodo', 'Tariffa a notte', 'Soggiorno minimo', ''],
    onRequest: 'Su richiesta', from: 'da', perNight: '/ notte', perWeek: 'a settimana',
    askRate: 'Chiedi la tariffa', ask: 'Richiedi', current: 'Stagione in corso',
    minNull: 'Da concordare', minN: '{n} notti',
    changeover: 'Arrivi e partenze di {day}',
    noteHouse: 'Prezzi per la casa intera. Tariffe comunicate con il preventivo.',
    noteIndicative: 'Periodi e tariffe indicativi, confermati nel preventivo.',
    updated: 'Tariffe aggiornate al {date}',
    statementTitle: 'Tariffe per la casa intera, preventivo su misura',
    statementLine: 'La tariffa dipende dal periodo e dalla durata del soggiorno. Scrivici le date: ti rispondiamo con disponibilità e preventivo.',
    and: ' e ', fromDay: 'dal', toDay: 'al',
    summaryOnRequest: 'Tariffa su richiesta', summaryFrom: 'da {price} / notte', summaryWhole: 'Casa intera, fino a 6 ospiti',
    summaryMicro: 'Nessun pagamento richiesto per inviare la richiesta.',
    estimator: {
      open: 'Calcola il soggiorno', title: 'Stima del soggiorno', nights: '{n} notti', night: '1 notte',
      total: 'Totale indicativo', quote: 'Per queste date ti inviamo noi il preventivo.',
      micro: 'Stima indicativa e non vincolante. Il prezzo definitivo è quello del preventivo.',
      minStay: 'In questo periodo il soggiorno minimo è di {n} notti. Invia comunque la richiesta, valutiamo volentieri le tue date.',
      tax: 'Imposta di soggiorno, esclusa: {amount}', cta: 'Richiedi questo soggiorno', taxExcluded: 'imposta di soggiorno esclusa',
    },
    months: ['gennaio', 'febbraio', 'marzo', 'aprile', 'maggio', 'giugno', 'luglio', 'agosto', 'settembre', 'ottobre', 'novembre', 'dicembre'],
    days: ['domenica', 'lunedì', 'martedì', 'mercoledì', 'giovedì', 'venerdì', 'sabato'],
  },
  gallery: {
    filters: { all: 'Tutte', interni: 'Interni', camere: 'Camere', bagni: 'Bagni', esterni: 'Esterni', dintorni: 'Dintorni' },
    count: '{n} fotografie', label: 'Galleria fotografica', prev: 'Foto precedente', next: 'Foto successiva', open: 'Apri la foto',
    filterLabel: 'Filtra le foto',
  },
  hero: {
    label: 'Fotografie della casa', slide: '{n} di {total}', prev: 'Foto precedente', next: 'Foto successiva',
    pause: 'Pausa presentazione', play: 'Riprendi presentazione',
  },
  map: {
    load: 'Carica la mappa (OpenStreetMap)', note: 'Caricando la mappa ti colleghi a openstreetmap.org.', title: 'Mappa: Contrada Trave 125',
  },
  distancesNote: 'Distanze indicative.',

  pages: {
    home: {
      title: 'Casa vacanze al Conero a 600 m dal mare | Casa in Campagna',
      desc: 'Casa vacanze intera a Montacuto (Ancona): 110 m², fino a 6 ospiti, giardino e parcheggio privato. A 1,1 km da Mezzavalle e circa 5 km da Portonovo. Scrivici le date.',
      eyebrow: 'Casa vacanze sul Monte Conero',
      h1: 'Una casa di campagna tra il Conero e il mare',
      lead: 'Casa intera, 110 m², fino a 6 ospiti. A 600 m dallo Scoglio del Trave.',
      discover: 'Scopri la casa',
      intro: {
        eyebrow: 'La casa',
        h2: 'Travi a vista, cotto e il Conero dalla finestra',
        text: 'Al Trave, sopra la costa del Conero, una casa intera solo per voi: due camere e un divano letto, due bagni, una cucina abitabile e un soggiorno con camino. Fuori, un giardino recintato e il parcheggio privato.',
        text2: 'Il mare è a pochi passi: la spiaggia di {mezzavalle} è a 1,1 km, la baia di {portonovo} a circa 5 km.',
      },
      spaces: {
        eyebrow: 'Gli spazi', h2: 'Tutto lo spazio di una casa', link: 'Tutta la casa',
        items: [
          ['soggiorno-travi', 'Soggiorno con camino', 'Un grande tavolo, i divani e il camino sotto le travi di legno.'],
          ['camera-matrimoniale', 'Due camere', 'Una matrimoniale e una con due letti singoli, più un divano letto.'],
          ['giardino-palma-mare', 'Giardino recintato', 'Prato, palme e uno scorcio di mare, sicuro per bambini e animali.'],
        ],
      },
      garden: {
        eyebrow: 'Fuori', h2: 'Il giardino e la vista',
        text: 'Il giardino è recintato e guarda il Monte Conero, con uno scorcio di mare tra gli alberi. Gli animali sono ammessi senza supplemento e la macchina resta nel parcheggio privato con sbarra.',
      },
      horizon: { eyebrow: 'Dintorni', h2: 'Il mare del Conero, a pochi passi', link: 'Esplora i dintorni' },
      rates: {
        eyebrow: 'Tariffe', h2: 'Prezzi per stagione', note: 'Tariffe per la casa intera, fino a 6 ospiti.',
        see: 'Vedi le tariffe', quote: 'Richiedi un preventivo',
      },
      amenities: { eyebrow: 'Servizi', h2: 'Quello che trovi in casa', link: 'Tutti i servizi' },
      faq: { eyebrow: 'Domande', h2: 'Domande frequenti' },
    },

    casa: {
      title: 'Casa per 6 al Conero con giardino | Casa in Campagna',
      desc: 'Casa di 110 m² con travi a vista: camera matrimoniale, camera con due letti, divano letto, 2 bagni, cucina, camino e giardino recintato con vista sul Conero.',
      eyebrow: 'La casa', h1: 'Casa vacanze per 6 al Conero, con giardino',
      lead: 'Casa intera di 110 m² con travi a vista, cotto e camino.',
      spec: {
        eyebrow: 'In breve', h2: 'La casa in numeri',
        rows: [
          ['Superficie', '110 m², casa intera'], ['Ospiti', 'fino a 6'], ['Camere', '2'],
          ['Letti', '1 matrimoniale, 2 singoli, 1 divano letto'], ['Bagni', '2, uno con vasca e uno con doccia'],
          ['Ingresso', 'indipendente, con parcheggio privato'],
        ],
      },
      spaces: {
        eyebrow: 'Gli spazi', h2: 'Stanza per stanza',
        items: [
          { n: '01', h: 'Soggiorno con camino', p: 'Il cuore della casa: un grande tavolo da pranzo, due divani, la TV e il camino, sotto un soffitto di travi in legno.', facts: ['Camino', 'Divano letto', 'TV a schermo piatto'], photos: ['soggiorno-travi', 'soggiorno-camino'] },
          { n: '02', h: 'Cucina abitabile', p: 'Una cucina con tavolo, dove preparare colazioni e cene come a casa.', facts: ['Piano cottura e forno', 'Microonde e frigorifero', 'Set per tè e caffè'], photos: ['cucina'] },
          { n: '03', h: 'Camera matrimoniale', p: 'Ampia e luminosa, con travi a vista, armadio e aria condizionata.', facts: ['Letto matrimoniale', 'Aria condizionata', 'Armadio'], photos: ['camera-matrimoniale', 'camera-matrimoniale-armadio'] },
          { n: '04', h: 'Camera con due letti singoli', p: 'Adatta a bambini o amici, con armadio e finestra sul verde.', facts: ['Due letti singoli', 'Armadio'], photos: ['camera-doppia', 'camera-doppia-armadio'] },
          { n: '05', h: 'Due bagni', p: 'Uno con vasca e lavatrice, uno con doccia. In entrambi bidet, asciugacapelli e set di cortesia.', facts: ['Vasca', 'Doccia', 'Asciugacapelli'], photos: ['bagno-vasca', 'bagno-doccia', 'bagno-secondo'], triptych: 'Due bagni: uno con vasca, uno con doccia' },
          { n: '06', h: 'Divano letto', p: 'In soggiorno c\'è un divano letto per il quinto e il sesto ospite.', facts: ['Fino a 6 ospiti in tutto'], photos: [] },
          { n: '07', h: 'Giardino e parcheggio', p: 'Il giardino recintato guarda il Monte Conero, con uno scorcio di mare. All\'ingresso, il parcheggio privato con sbarra.', facts: ['Giardino recintato', 'Vista sul Conero', 'Parcheggio gratuito'], photos: ['giardino-vista-conero', 'giardino-palma-mare', 'parcheggio-privato'] },
        ],
        toRates: 'Vedi prezzi e disponibilità',
      },
      amenities: {
        eyebrow: 'Servizi', h2: 'Servizi e regole della casa',
        groups: { dentro: 'Dentro', fuori: 'Fuori', regole: 'Regole', no: 'Non disponibile' },
      },
    },

    galleria: {
      title: 'Foto della casa vacanze al Conero | Casa in Campagna',
      desc: '17 foto della casa vacanze al Trave: soggiorno con camino, camere, cucina, bagni, giardino con vista sul Monte Conero e la spiaggia di Mezzavalle.',
      eyebrow: 'Galleria', h1: 'Foto della casa e del giardino al Conero',
      lead: 'Gli interni, il giardino e il mare a pochi passi.',
      intro: 'La casa ha un soggiorno con camino e travi a vista, una cucina abitabile, una camera matrimoniale, una camera con due letti singoli e due bagni. Fuori c\'è un giardino recintato con vista sul Monte Conero e uno scorcio di mare. Qui sotto trovi anche la spiaggia di Mezzavalle, a 1,1 km dalla casa.',
      inline: 'Ti piace la casa? Verifica le tue date',
    },

    dintorni: {
      title: 'Mezzavalle, Portonovo e dintorni | Casa in Campagna',
      desc: 'Scoglio del Trave a 600 m, spiaggia di Mezzavalle a 1,1 km, Portonovo a circa 5 km, Ancona a 6,6 km. Come arrivare in auto, treno e aereo alla casa vacanze.',
      eyebrow: 'Dintorni', h1: 'Mezzavalle, Portonovo e le spiagge del Conero vicino alla casa',
      lead: 'La casa è sopra la costa del Conero, tra il Trave e Ancona.',
      distances: { eyebrow: 'Distanze', h2: 'Quanto dista' },
      places: { eyebrow: 'Luoghi', h2: 'Il mare e la città' },
      arrive: {
        eyebrow: 'Come arrivare', h2: 'In auto, in treno, in aereo',
        car: ['In auto', 'Il navigatore porta a Contrada Trave 125, Montacuto. In casa c\'è il parcheggio privato gratuito con sbarra.'],
        train: ['In treno', 'Stazione di Ancona, a 6,6 km dalla casa.'],
        plane: ['In aereo', 'Aeroporto di Ancona, a 19 km dalla casa.'],
      },
      map: { eyebrow: 'Mappa', h2: 'Dove siamo' },
      tips: { eyebrow: 'Consigli', h2: 'I consigli di chi ti ospita' },
    },

    prezzi: {
      title: 'Prezzi casa vacanze Conero per stagione | Casa in Campagna',
      desc: 'Tariffe per stagione della casa intera fino a 6 ospiti, al Conero. Richiedi disponibilità e preventivo per le tue date: ti risponde direttamente chi ti ospita.',
      descPrices: 'Casa vacanze al Conero da {price} a notte per la casa intera, fino a 6 ospiti. Tariffe per stagione, richiedi disponibilità e preventivo.',
      eyebrow: 'Tariffe', h1: 'Prezzi e disponibilità della casa vacanze al Conero',
      lead: 'Tariffe per la casa intera, fino a 6 ospiti. Scrivici le tue date per un preventivo preciso.',
      seasons: { eyebrow: 'Stagioni', h2: 'Il momento giusto per il Conero', intro: 'La tariffa è per la casa intera, fino a 6 ospiti.' },
      included: {
        eyebrow: 'Cosa è incluso', h2: 'Incluso e da sapere', always: 'Sempre incluso', know: 'Da sapere',
        cleaning: 'Pulizia finale', cleaningIncluded: 'Inclusa', cleaningAmount: '{amount}',
        tax: 'Imposta di soggiorno', taxText: 'Imposta di soggiorno del Comune di Ancona non inclusa, importo indicato nel preventivo.',
        taxAmount: '{amount} a persona a notte, non inclusa',
        deposit: 'Deposito cauzionale', cots: 'Culle e letti aggiuntivi', cotsText: 'Non disponibili',
        smoking: 'Fumo', smokingText: 'Non si fuma all\'interno della casa',
        payment: 'Pagamento', terms: 'Condizioni comunicate con il preventivo.',
      },
      how: {
        eyebrow: 'Come si prenota', h2: 'Tre passaggi, con una persona vera dall\'altra parte',
        steps: [
          ['Scrivici le date', 'Arrivo, partenza e numero di ospiti, con il modulo, su WhatsApp o per telefono.'],
          ['Ricevi il preventivo', 'Ti rispondiamo con la disponibilità e il prezzo per la casa intera.'],
          ['Conferma', 'Le condizioni di pagamento e cancellazione sono indicate nel preventivo.'],
        ],
        confirm: 'Riceverai una conferma scritta con date, importo e condizioni.',
      },
      quote: {
        eyebrow: 'Preventivo', h2: 'Richiedi un preventivo',
        tiles: [['Scrivi una mail', 'Compila il modulo qui sotto'], ['Chiama', ''], ['WhatsApp', 'Scrivici un messaggio']],
      },
      faq: { eyebrow: 'Domande', h2: 'Domande sulle tariffe' },
      portal: 'Preferisci un portale? Ci trovi anche su',
    },

    contatti: {
      title: 'Contatti e prenotazioni, Montacuto | Casa in Campagna',
      desc: '{address}. {channels} e modulo con date di arrivo e partenza per la casa vacanze al Conero.',
      channels: { phone: 'Telefono', whatsapp: 'WhatsApp', email: 'email' },
      eyebrow: 'Contatti', h1: 'Contatti e prenotazioni',
      lead: 'Scrivi direttamente a chi ti ospita: rispondiamo in italiano e in inglese.',
      card: { title: 'Contatti diretti', address: 'Indirizzo', times: 'Orari', cin: 'CIN', langs: 'Lingue', langsText: 'Italiano, inglese' },
      map: { eyebrow: 'Come arrivare', h2: 'Dove siamo', station: 'Stazione di Ancona', airport: 'Aeroporto di Ancona', more: 'Tutte le indicazioni' },
      arrival: { eyebrow: 'Arrivo', h2: 'Il giorno dell\'arrivo', text: 'Check-in dalle 15:00, check-out entro le 10:00. Comunicaci in anticipo l\'orario di arrivo.' },
    },

    privacy: {
      title: 'Privacy e cookie | Casa in Campagna', desc: 'Informativa privacy e cookie del sito della Casa in Campagna al Trave.',
      eyebrow: 'Informativa', h1: 'Privacy e cookie',
      lead: 'Come usiamo i dati che ci mandi con il modulo di richiesta.',
      sections: [
        ['Titolare del trattamento', '{controller}'],
        ['Quali dati', 'Nome, email, telefono se lo indichi, date del soggiorno, numero di ospiti e il messaggio che scrivi.'],
        ['Perché', 'Solo per rispondere alla tua richiesta e preparare il preventivo (art. 6.1.b GDPR, misure precontrattuali).'],
        ['Per quanto tempo', '{retention}'],
        ['A chi', 'I dati non vengono ceduti a terzi. Possono passare dal fornitore del servizio email o del modulo: {provider}.'],
        ['I tuoi diritti', 'Puoi chiedere accesso, rettifica, cancellazione o limitazione dei dati scrivendo al titolare. Puoi proporre reclamo al Garante per la protezione dei dati personali.'],
      ],
      cookieTitle: 'Cookie',
      cookie: 'Questo sito non usa cookie di profilazione né cookie di terze parti. I caratteri sono ospitati sul sito stesso. La mappa viene caricata da OpenStreetMap solo se premi il pulsante apposito.',
      missing: 'da completare con i dati del titolare',
    },

    notFound: {
      title: 'Pagina non trovata | Casa in Campagna', h1: 'Pagina non trovata',
      lead: 'La pagina che cerchi non esiste o è stata spostata.', home: 'Torna alla home', en: 'Page not found. English home',
    },
  },
};
